const SESSIONS_SCHEDULE_DATA = [
  {
    package_clone_id: 1480,
    minutes: 30,
    original_minutes: 30,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 1438,
    instructor_name: 'Ahmed Gamil',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 5,
    instructor_reviews: 32,
  },
  {
    package_clone_id: 1777,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'IELTS ',
    package_clone_field_id: 219,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 2312,
    instructor_name: 'TYRO TRIAL',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 0,
    instructor_reviews: 0,
  },
  {
    package_clone_id: 1993,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 2312,
    instructor_name: 'TYRO TRIAL',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 0,
    instructor_reviews: 0,
  },
  {
    package_clone_id: 2353,
    minutes: 30,
    original_minutes: 30,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 2907,
    instructor_name: 'Benedetta Lazzari',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 5,
    instructor_reviews: 15,
  },
  {
    package_clone_id: 2555,
    minutes: 300,
    original_minutes: 300,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 5887,
    instructor_name: 'New Testing',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/5887/thumb/data?1588715375',
    instructor_rating: 0,
    instructor_reviews: 0,
  },
  {
    package_clone_id: 2557,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'Business English ',
    package_clone_field_id: 221,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 3716,
    instructor_name: 'Mahmoud Al Najjar',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 5,
    instructor_reviews: 3,
  },
  {
    package_clone_id: 2558,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 3716,
    instructor_name: 'Mahmoud Al Najjar',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 5,
    instructor_reviews: 3,
  },
  {
    package_clone_id: 2560,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 3716,
    instructor_name: 'Mahmoud Al Najjar',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 5,
    instructor_reviews: 3,
  },
  {
    package_clone_id: 2563,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 3716,
    instructor_name: 'Mahmoud Al Najjar',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 5,
    instructor_reviews: 3,
  },
  {
    package_clone_id: 2567,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 676,
    instructor_name: 'Samar Hassan',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 4,
    instructor_reviews: 31,
  },
  {
    package_clone_id: 2570,
    minutes: 600,
    original_minutes: 600,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 5475,
    instructor_name: 'Hager Ali',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 5,
    instructor_reviews: 0,
  },
  {
    package_clone_id: 2572,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 3714,
    instructor_name: 'Abubaker Ghazaly',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/1589/thumb/14037457_951945568285489_810432986_o.jpg?1565117646',
    instructor_rating: 4,
    instructor_reviews: 11,
  },
  {
    package_clone_id: 2578,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 676,
    instructor_name: 'Samar Hassan',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 4,
    instructor_reviews: 31,
  },
  {
    package_clone_id: 2588,
    minutes: 540,
    original_minutes: 600,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 5858,
    instructor_name: 'Instructor (Mob);',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 3,
    instructor_reviews: 61,
  },
  {
    package_clone_id: 2648,
    minutes: 60,
    original_minutes: 300,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 1471,
    instructor_name: 'TyroTutor Testing',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1471/thumb/data?1592932223',
    instructor_rating: 3,
    instructor_reviews: 62,
  },
  {
    package_clone_id: 2649,
    minutes: 750,
    original_minutes: 1200,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 1471,
    instructor_name: 'TyroTutor Testing',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1471/thumb/data?1592932223',
    instructor_rating: 3,
    instructor_reviews: 62,
  },
  {
    package_clone_id: 2653,
    minutes: 180,
    original_minutes: 300,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 1471,
    instructor_name: 'TyroTutor Testing',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1471/thumb/data?1592932223',
    instructor_rating: 3,
    instructor_reviews: 62,
  },
  {
    package_clone_id: 2654,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 5858,
    instructor_name: 'Instructor (Mob);',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2312/thumb/data?1572873236',
    instructor_rating: 3,
    instructor_reviews: 61,
  },
  {
    package_clone_id: 2658,
    minutes: 60,
    original_minutes: 60,
    package_clone_field: 'English ',
    package_clone_field_id: 201,
    student_id: 1466,
    student_name: 'StudentTyro Student 1',
    student_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1466/thumb/data?1590035232',
    instructor_id: 1471,
    instructor_name: 'TyroTutor Testing',
    instructor_image:
      'https://s3-eu-west-1.amazonaws.com/tyroeg/staging-tyro/users/imgs/1471/thumb/data?1592932223',
    instructor_rating: 3,
    instructor_reviews: 62,
  },
];

export default SESSIONS_SCHEDULE_DATA;
