const Instructors = [
  {
    id: 2,
    full_name: 'Leen Kamal',
    available: true,
    online: false,
    about: '',
    rate_to_display: 160.0,
    number_of_reviews: 5,
    average_rating: 3.7,
    number_of_sessions: 73,
    number_of_students: 16,
    video: 'c9isjKzeC-o',
    profile_picture_medium:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/79605/medium/data?1627916439',
    bio: 'hello there',
    instructor_fields: ['English '],
    tutor_fields: [[201, 'English ']],
    tutor_reviews: [
      {
        id: 2972,
        student: 'Moustafa Elstouhi',
        rating: 5,
        text: '<p>They are professionals and I learned a lot of grammars and Linguistics which helped me to improve my language.</p><p data-f-id="pbf" style="text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;">Powered by <a href="https://www.froala.com/wysiwyg-editor?pb=1" title="Froala Editor">Froala Editor</a></p>',
        created_at: '2021-10-07T00:03:58.000+02:00',
      },
      {
        id: 2971,
        student: 'Omar Abdulaziz',
        rating: 4,
        text: '<p>Hello There this is my review.</p><p data-f-id="pbf" style="text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;">Powered by <a href="https://www.froala.com/wysiwyg-editor?pb=1" title="Froala Editor">Froala Editor</a></p>',
        created_at: '2021-10-07T00:03:49.000+02:00',
      },
      {
        id: 2970,
        student: 'Moustafa Elstouhi',
        rating: 2,
        text: '',
        created_at: '2021-10-07T00:03:42.000+02:00',
      },
      {
        id: 2969,
        student: 'Moustafa Elstouhi',
        rating: 5,
        text: '',
        created_at: '2021-10-07T00:03:33.000+02:00',
      },
      {
        id: 2968,
        student: 'Moustafa Elstouhi',
        rating: 0,
        text: '',
        created_at: '2021-10-07T00:03:27.000+02:00',
      },
    ],
    free_trial: { enabled: true, claimed: false },
    tutor_packages: [
      {
        id: 1804,
        type: 'DefaultPackage',
        minutes: 60,
        time_in_hours: 1.0,
        rate: 160.0,
        offline_rate: 0.0,
        tutor_user_id: 79605,
        deleted_at: null,
      },
      {
        id: 1805,
        type: 'TrialPackage',
        minutes: 30,
        time_in_hours: 0.5,
        rate: 60.0,
        offline_rate: 0.0,
        tutor_user_id: 79605,
        deleted_at: null,
      },
      {
        id: 1806,
        type: 'NormalPackage',
        minutes: 300,
        time_in_hours: 5.0,
        rate: 150.0,
        offline_rate: 0.0,
        tutor_user_id: 79605,
        deleted_at: null,
      },
      {
        id: 1807,
        type: 'NormalPackage',
        minutes: 600,
        time_in_hours: 10.0,
        rate: 140.0,
        offline_rate: 0.0,
        tutor_user_id: 79605,
        deleted_at: null,
      },
      {
        id: 1828,
        type: 'NormalPackage',
        minutes: 960,
        time_in_hours: 16.0,
        rate: 130.0,
        offline_rate: 0.0,
        tutor_user_id: 79605,
        deleted_at: null,
      },
      {
        id: 1942,
        type: 'NormalPackage',
        minutes: 2400,
        time_in_hours: 40.0,
        rate: 100.0,
        offline_rate: 0.0,
        tutor_user_id: 79605,
        deleted_at: null,
      },
    ],
  },
  {
    id: 3,
    full_name: 'Benedetta Lazzari',
    available: true,
    online: false,
    about:
      'My name is Benedetta, I’m 29, I’m Italian and I’m an English certified teacher. \r\nI have attended Grammar School where I have studied Latin and Ancient Greek, then I have studied Translation and Interpreting between English,Italian and Spanish. I have been trained at International House Rome, where as a trainee English teacher I have taught multilevel and multilingual groups of students, and I have obtained the most widely recognised teaching qualification, Cambridge CELTA. \r\nI also hold other 4 Cambridge certificates: 3 level certificates with high scores (B1,B2,C1/C2) and a Cambridge Teaching Pronunciation certificate. I teach General English Skills (Reading-Listening-Writing and Speaking) and Systems (Grammar and Vocabulary) during individual lessons. As for groups, I give Conversation English classes (Speaking and Listening). \r\nI have been working as a Freelance English Teacher since 2017, teaching one-to-one lessons and doing Cambridge exams preparation and tutoring. \r\nI’m going to help you progress from one level of the CEFR (Common European Framework of Reference) to the next (A2.1 -\u003e A2.2 -\u003e B1.1 -\u003e B1.2 -\u003e B2.1 -\u003e B2.2) so from being a Basic to become an Independent User.\r\n\r\n***Lessons delivered in BRITISH English***\r\n',
    rate_to_display: 200.0,
    number_of_reviews: 173,
    average_rating: 5,
    number_of_sessions: 1700,
    number_of_students: 248,
    video: 'jc4jXXnriko',
    profile_picture_medium:
      'https://s3-eu-west-1.amazonaws.com/tyro-app/tyro-app/users/imgs/2907/medium/data?1614007889',
    bio: '',
    instructor_fields: ['English '],
    tutor_fields: [[201, 'English ']],
    tutor_reviews: [
      {
        id: 2972,
        student: 'Moustafa Elstouhi',
        rating: 5,
        text: '',
        created_at: '2021-10-07T00:03:58.000+02:00',
      },
      {
        id: 2971,
        student: 'Moustafa Elstouhi',
        rating: 5,
        text: '',
        created_at: '2021-10-07T00:03:49.000+02:00',
      },
      {
        id: 2970,
        student: 'Moustafa Elstouhi',
        rating: 5,
        text: '',
        created_at: '2021-10-07T00:03:42.000+02:00',
      },
      {
        id: 2969,
        student: 'Moustafa Elstouhi',
        rating: 5,
        text: '',
        created_at: '2021-10-07T00:03:33.000+02:00',
      },
      {
        id: 2968,
        student: 'Moustafa Elstouhi',
        rating: 5,
        text: '',
        created_at: '2021-10-07T00:03:27.000+02:00',
      },
    ],
    free_trial: { enabled: true, claimed: false },
    tutor_packages: [
      {
        id: 651,
        type: 'DefaultPackage',
        minutes: 60,
        time_in_hours: 1.0,
        rate: 200.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 652,
        type: 'TrialPackage',
        minutes: 30,
        time_in_hours: 0.5,
        rate: 0.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 654,
        type: 'NormalPackage',
        minutes: 600,
        time_in_hours: 10.0,
        rate: 180.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 1168,
        type: 'NormalPackage',
        minutes: 1200,
        time_in_hours: 20.0,
        rate: 170.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 1169,
        type: 'NormalPackage',
        minutes: 2160,
        time_in_hours: 36.0,
        rate: 160.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 1212,
        type: 'NormalPackage',
        minutes: 720,
        time_in_hours: 12.0,
        rate: 180.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 1283,
        type: 'NormalPackage',
        minutes: 3000,
        time_in_hours: 50.0,
        rate: 155.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 1459,
        type: 'NormalPackage',
        minutes: 1440,
        time_in_hours: 24.0,
        rate: 170.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 1461,
        type: 'NormalPackage',
        minutes: 1800,
        time_in_hours: 30.0,
        rate: 160.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 1462,
        type: 'NormalPackage',
        minutes: 2880,
        time_in_hours: 48.0,
        rate: 150.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
      {
        id: 1604,
        type: 'NormalPackage',
        minutes: 300,
        time_in_hours: 5.0,
        rate: 190.0,
        offline_rate: 0.0,
        tutor_user_id: 2907,
        deleted_at: null,
      },
    ],
  },
  {
    id: 79790,
    full_name: 'Zenhom Mohamed N',
    available: true,
    online: null,
    about: '',
    rate_to_display: 0.0,
    number_of_reviews: 1,
    average_rating: 5,
    number_of_sessions: 93,
    number_of_students: 10,
    video: '',
    profile_picture_medium: '',
    bio: null,
    instructor_fields: ['Math', 'Physics'],
    tutor_fields: [
      [292, 'Math'],
      [257, 'Physics'],
    ],
    tutor_reviews: [
      {
        id: 2751,
        student: 'Jana Mohamed prep N',
        rating: 5,
        text: '',
        created_at: '2021-08-19T19:19:13.000+02:00',
      },
    ],
    free_trial: { enabled: true, claimed: false },
    tutor_packages: [
      {
        id: 1874,
        type: 'DefaultPackage',
        minutes: 0,
        time_in_hours: 0.0,
        rate: 0.0,
        offline_rate: 0.0,
        tutor_user_id: 79790,
        deleted_at: null,
      },
      {
        id: 1875,
        type: 'TrialPackage',
        minutes: 30,
        time_in_hours: 0.5,
        rate: 0.0,
        offline_rate: 0.0,
        tutor_user_id: 79790,
        deleted_at: null,
      },
      {
        id: 1884,
        type: 'NormalPackage',
        minutes: 300,
        time_in_hours: 5.0,
        rate: 120.0,
        offline_rate: 0.0,
        tutor_user_id: 79790,
        deleted_at: null,
      },
      {
        id: 1920,
        type: 'NormalPackage',
        minutes: 960,
        time_in_hours: 16.0,
        rate: 120.0,
        offline_rate: 0.0,
        tutor_user_id: 79790,
        deleted_at: null,
      },
      {
        id: 1921,
        type: 'NormalPackage',
        minutes: 480,
        time_in_hours: 8.0,
        rate: 120.0,
        offline_rate: 0.0,
        tutor_user_id: 79790,
        deleted_at: null,
      },
      {
        id: 1924,
        type: 'NormalPackage',
        minutes: 120,
        time_in_hours: 2.0,
        rate: 100.0,
        offline_rate: 0.0,
        tutor_user_id: 79790,
        deleted_at: null,
      },
      {
        id: 1978,
        type: 'NormalPackage',
        minutes: 60,
        time_in_hours: 1.0,
        rate: 160.0,
        offline_rate: 0.0,
        tutor_user_id: 79790,
        deleted_at: null,
      },
      {
        id: 2047,
        type: 'NormalPackage',
        minutes: 240,
        time_in_hours: 4.0,
        rate: 160.0,
        offline_rate: 0.0,
        tutor_user_id: 79790,
        deleted_at: null,
      },
    ],
  },
  {
    id: 79888,
    full_name: 'Mohamed  Elsherbiny N',
    available: true,
    online: null,
    about: '',
    rate_to_display: 0.0,
    number_of_reviews: 0,
    average_rating: null,
    number_of_sessions: 75,
    number_of_students: 6,
    video: '',
    profile_picture_medium: '',
    bio: null,
    instructor_fields: ['social studies'],
    tutor_fields: [[296, 'social studies']],
    tutor_reviews: [],
    free_trial: { enabled: true, claimed: false },
    tutor_packages: [
      {
        id: 1909,
        type: 'DefaultPackage',
        minutes: 0,
        time_in_hours: 0.0,
        rate: 0.0,
        offline_rate: 0.0,
        tutor_user_id: 79888,
        deleted_at: null,
      },
      {
        id: 1910,
        type: 'TrialPackage',
        minutes: 30,
        time_in_hours: 0.5,
        rate: 0.0,
        offline_rate: 0.0,
        tutor_user_id: 79888,
        deleted_at: null,
      },
      {
        id: 1911,
        type: 'NormalPackage',
        minutes: 480,
        time_in_hours: 8.0,
        rate: 111.0,
        offline_rate: 0.0,
        tutor_user_id: 79888,
        deleted_at: null,
      },
      {
        id: 1935,
        type: 'NormalPackage',
        minutes: 180,
        time_in_hours: 3.0,
        rate: 160.0,
        offline_rate: 0.0,
        tutor_user_id: 79888,
        deleted_at: null,
      },
      {
        id: 1946,
        type: 'NormalPackage',
        minutes: 480,
        time_in_hours: 8.0,
        rate: 90.0,
        offline_rate: 0.0,
        tutor_user_id: 79888,
        deleted_at: null,
      },
      {
        id: 1967,
        type: 'NormalPackage',
        minutes: 480,
        time_in_hours: 8.0,
        rate: 180.0,
        offline_rate: 0.0,
        tutor_user_id: 79888,
        deleted_at: null,
      },
      {
        id: 2030,
        type: 'NormalPackage',
        minutes: 540,
        time_in_hours: 9.0,
        rate: 180.0,
        offline_rate: 0.0,
        tutor_user_id: 79888,
        deleted_at: null,
      },
    ],
  },
];

export default Instructors;
